# Generated by Django 4.2 on 2024-02-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_checkout_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='checkout_session',
            new_name='checkout_session_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent',
            new_name='stripe_payment_intent_id',
        ),
    ]
