# Generated by Django 4.2 on 2024-02-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
