# Generated by Django 4.2 on 2024-02-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menu_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
