# Generated by Django 4.2 on 2024-02-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_taken_by',
            new_name='order_placed_by',
        ),
    ]
